sudo: false
language: java

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy"
  skip_cleanup: true

notifications:
  email:
    on_success: never
    on_failure: change